name: Doge Price Bot

on:
  schedule:
    - cron: '*/15 * * * *'  # every 15 minutes UTC
  workflow_dispatch:        # manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: node bot.js
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          API_KEY: ${{ secrets.API_KEY }}
