name: Generate SSH Keypair

on:
  workflow_dispatch:

jobs:
  generate-key:
    runs-on: ubuntu-latest

    steps:
      - name: Generate SSH keypair
        id: generate
        run: |
          ssh-keygen -t ed25519 -C "github-actions" -f key -N ""
          echo "PRIVATE_KEY<<EOF" >> $GITHUB_OUTPUT
          cat key >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "PUBLIC_KEY<<EOF" >> $GITHUB_OUTPUT
          cat key.pub >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Show Private Key (copy this and save securely)
        run: echo "$PRIVATE_KEY"

      - name: Show Public Key (add this to your server authorized_keys)
        run: echo "$PUBLIC_KEY"
