name: Generate SSH Keypair

on:
  workflow_dispatch:

jobs:
  generate-key:
    runs-on: ubuntu-latest

    steps:
      - name: Generate SSH keypair
        id: generate
        run: |
          ssh-keygen -t ed25519 -C "github-actions" -f key -N ""
          echo "PRIVATE_KEY<<EOF" >> $GITHUB_ENV
          cat key >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "PUBLIC_KEY<<EOF" >> $GITHUB_ENV
          cat key.pub >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Output Private Key (save securely)
        run: |
          echo "${PRIVATE_KEY}"

      - name: Output Public Key (add to authorized_keys)
        run: |
          echo "${PUBLIC_KEY}"
