name: Update Discord Bot Status Remotely

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes (was incorrectly labeled)
  workflow_dispatch:

jobs:
  update-remote:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p "${{ secrets.SERVER_PORT }}" "${{ secrets.SERVER_HOST }}" >> ~/.ssh/known_hosts

      - name: Run update-status.js remotely
        run: |
          ssh -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
          "cd /full/path/to/your/crypto-discord-tracker && node update-status.js"
