name: Update Bot Status

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes UTC
  workflow_dispatch:

jobs:
  update-status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install

      - name: Run update-status.js
        run: node update-status.js
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
